/**
 * DEVELOPMENT WEBPACK CONFIGURATION
 */

import path from 'path'
import webpack from 'webpack'
import HtmlWebpackPlugin from 'html-webpack-plugin'
import CircularDependencyPlugin from 'circular-dependency-plugin'
import CopyWebpackPlugin from 'copy-webpack-plugin'

import base from './webpack.base.babel.mjs'

import * as constants from '#constants'

export default base({
  mode: 'development',

  // Add hot reloading in development
  entry: [path.join(process.cwd(), 'src/index.js')],

  // Don't use hashes in dev mode for better performance
  output: {
    filename: '[name].js',
    chunkFilename: '[name].chunk.js'
  },

  optimization: {
    splitChunks: {
      chunks: 'all'
    }
  },

  // Add development plugins
  plugins: [
    new webpack.HotModuleReplacementPlugin(), // Tell webpack we want hot reloading
    new HtmlWebpackPlugin({
      inject: true, // Inject all files that are generated by webpack, e.g. bundle.js
      template: 'src/index.html',
      favicon: 'resources/favicon.ico'
    }),
    new webpack.DefinePlugin({
      IS_DEV: !process.env.NC_DEV_LIVE,
      REPO: JSON.stringify(constants.repo)
    }),
    new CircularDependencyPlugin({
      exclude: /a\.js|node_modules/, // exclude node_modules
      failOnError: false // show a warning when there is a circular dependency
    }),
    new CopyWebpackPlugin({
      patterns: [
        { from: 'locales', to: 'locales' },
        { from: 'resources', to: 'resources' }
      ]
    })
  ],

  // Emit a source map for easier debugging
  // See https://webpack.js.org/configuration/devtool/#devtool
  devtool: 'eval-source-map',

  performance: {
    hints: false
  }
})
